version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: my_web
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
